stages:
  - build
  - push
  - deploy

build_image_dev:
  stage: build
  only:
    - dev
  tags:
    - runner-dev02
  script:
    - docker-compose -f ./docker-compose.yml down
    #- docker rmi registry.digitalexchange.id/digitalexchange/arbitgo-web:dev
    - docker build --no-cache -t registry.digitalexchange.id/digitalexchange/arbitgo-web:dev .

push_image_dev:
  stage: push
  only:
    - dev
  tags:
    - runner-dev02
  script:
    - docker push registry.digitalexchange.id/digitalexchange/arbitgo-web:dev 

deploy_image_dev:
  stage: deploy
  only:
    - dev
  tags:
    - runner-dev02
  script:
    - docker-compose -f ./docker-compose.yml up -d
