version: '3'
services:

    arbitgo-fe:
      image: 'registry.digitalexchange.id/digitalexchange/arbitgo-web:dev'
      restart: unless-stopped
      ports:
        - '3018:3018'
      networks:
        - arbitgo

networks:
    arbitgo:
      driver: bridge